import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Theme from "./components/Theme";
import InitColorSchemeScript from "@mui/material/InitColorSchemeScript";
import Navbar from "./components/Navbar";
import { Container } from "@mui/material";
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Personal Inventory App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable}`}>
				<InitColorSchemeScript></InitColorSchemeScript>
				<Theme>
					<Navbar />
					<Container>{children}</Container>
				</Theme>
			</body>
		</html>
	);
}
